---
- name: Create multiple nginx containers for load balancing
  hosts: all
  tasks:
    - name: Create 10 nginx contianer
      docker_container:
        image: nginx
        name: "contianer{{item}}"
      with_sequence: count=10
