---
- name: Download docker images
  hosts: all
  tasks:
    - name: Pull docker images form docker hub
      docker_image:
        name: "{{item}}"
        source: pull
      with_items:
        - nginx
        - ghost
        - ubuntu
        - busybox
        - tomcat
