---
- name: Implementing playscope variables
  hosts: all
  vars:
    - a: tomcat10
    - b: present
    - c: yes
  tasks:
    - name: Install/Unstall s/w app's
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
